import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import SearchBar from '../components/SearchBar'
import MyCountries from '../components/MyCountries'


export const getStaticProps = async () => {
  const res = await fetch("https://restcountries.com/v3.1/all")
  const data = await res.json()
  // console.log(data)
  return {
    props:{data}
  }

}


export default function Home({data}) {
  // console.log(data[0].name)

  return (
    <div className={styles.container}>
      <Head>
        <title>World Rank </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.countrytable_inner}> World Rank</h1>
      <SearchBar />
      <MyCountries country ={data}/>



    </div>
  )
}
